<a href="https://colab.research.google.com/github/Arjunmanoj13/AIML/blob/main/2303A52134AIMLAsgn1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
list = [1, 2, 3, 4, 5]
print(list)
print(type(list))

[1, 2, 3, 4, 5]
<class 'list'>


In [6]:
import numpy as np
list = [1, 2, 3, 4, 5]
print(list)
print(type(list))

[1, 2, 3, 4, 5]
<class 'list'>


In [9]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
multiplication = a * b
division = a / b
addition = a + b
subtraction = a - b
print(multiplication)
print(division)
print(addition)
print(subtraction)
print(np.power(a,b))

[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[      1     128    6561  262144 9765625]


In [7]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(str(array1))
print(str(array2))
print(str(array1 + array2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [8]:

print(np.sin(90))
print(np.log(90))
print(np.log2(90))
print(np.exp(90))

0.8939966636005579
4.499809670330265
6.491853096329675
1.2204032943178408e+39
